baseurl      = "localhost"
title        = "Dimitri's Fanastische Portfolio"
languageCode = "en-us"
theme        = "hugo-theme-hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jun 13, 2023"
  dateformShort   = "Jun 13"
  dateformNum     = "20023-06-013"
  dateformNumTime = "20023-06-013 15:04"

  # Subtitle for home
  homeSubtitle = "Dimitri's Portfolio"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "De Portfolio"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Dimitri's prachtige portfolio."
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Vakken"
    url        = "/posts"
